version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 22.x  # Specify the Node.js version you are using
    commands:
      # Install dependencies (if any)
      - echo "Installing npm dependencies..."
      - npm install
 
  pre_build:
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    commands:
      # Run tests (optional, if you have any)
      - echo "Running tests..."
      - npm run test  # If you have unit tests
      - echo "Running tests"
      - npm run test
      - echo "Running SonarCloud analysis"
      - npx sonar-scanner \
          -Dsonar.projectKey=wolverineanuj \
          -Dsonar.organization=wolverineanuj \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN  
 
  build:
    commands:
      # Create a zip file including everything in the root directory
      - echo "Zipping the whole application..."
      - zip -r book-store.zip .  # Zips the entire project folder (including node_modules, src, etc.)
 
      # Upload the zip file to S3
      - echo "Uploading book-store.zip to S3..."
      - aws s3 cp book-store.zip s3://bookstore-lambda-code/book-store.zip  # Replace with your S3 bucket name
 
  post_build:
    commands:
      # Deploy Lambda function from the S3 bucket
      - echo "Updating Lambda functions..."
 
      # Lambda Function 1
      - aws lambda update-function-code --function-name getBooks --s3-bucket bookstore-lambda-code --s3-key book-store.zip
      - echo "Lambda function 1 deployed successfully!"
      # Lambda Function 2
      - aws lambda update-function-code --function-name createBook --s3-bucket bookstore-lambda-code --s3-key book-store.zip
      - echo "Lambda function 2 deployed successfully!"
      # Lambda Function 3
      - aws lambda update-function-code --function-name updateBook --s3-bucket bookstore-lambda-code --s3-key book-store.zip
      - echo "Lambda function 3 deployed successfully!"
      # Lambda Function 4
      - aws lambda update-function-code --function-name deleteBook --s3-bucket bookstore-lambda-code --s3-key book-store.zip
      - echo "Lambda function 4 deployed successfully!"
 
artifacts:
  files:
    - '**/*'
  discard-paths: yes